{
  try {
    return call.call();
  }
 catch (  Exception e) {
    throw new ExecutionException(e);
  }
 finally {
    done=true;
  }
}
