{
  if (failMode == FailMode.AFTER_THROW_EXCEPTION) {
    throw new RuntimeException("induced!");
  }
}
