{
  assertTrue("Unexpected exception cause " + cause,condition);
}
