{
  if (fail)   throw new CacheException("Induced failure");
}
