{
  try {
    return CompletableFutures.await(future);
  }
 catch (  CompletionException e) {
    throw e.getCause();
  }
}
