{
  if (throwable.getCause() != null && throwable instanceof CompletionException) {
    throwable=throwable.getCause();
  }
  if (throwable instanceof CacheException) {
    log.trace("Replication exception",throwable);
    throw ((CacheException)throwable);
  }
 else {
    log.unexpectedErrorReplicating(throwable);
    throw new CacheException(throwable);
  }
}
